apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zsgj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zsgj
    app.kubernetes.io/part-of: ci1t-830-0052-app
  name: devfile-sample-zsgj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zsgj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zsgj
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0052-tenant/ci1t-830-0052-app/devfile-sample-zsgj@sha256:f3e0b8a1ada94da5d09f3d2521e90cb954f786eb6f34196c44135270e852b953
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
