apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zsgj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0052-tenant/ci1t-830-0052-app/devfile-sample-zsgj@sha256:f3e0b8a1ada94da5d09f3d2521e90cb954f786eb6f34196c44135270e852b953
        name: my-nodejs
        resources: {}
status: {}
